### ISSUE TITLE
Smooch User is not being created until first message is sent

### ISSUE THREAD

**Issue by khataha92** [smooch/smooch-android#103]
When opening the app, the `Smooch.login(...)` is called and returned with `success`, but the Smooch user is not created, and can't be accessed through the REST API. However, when sending the first smooch message, the user is created.

This was not the case previously in version `4.8.1`, it used to create the user immediately when `Smooch.login(...)`  is called without the need for the user to send a first message. This allowed us to initiate conversations with the users from our backend even if the user didn't start a conversation.

Can you please fix this issue and make it work as it used to be in version `4.8.1` i.e. (create the user directly on `Smooch.login`, instead of when he sends first message)

**Comment by mspensieri** [comment]
Hi @khataha92. This change is intended, and is the new behaviour on 5.x versions. This was mentioned in the [release notes](https://github.com/smooch/smooch-android/releases/tag/5.0.0) for v5.0.0

> This major version introduces a new optimized initialization sequence which changes when key events like creating an appUser or establishing a websocket connection are happening.

Alternatively, you can use the [pre-create user API](https://docs.smooch.io/rest/#pre-create-app-user) to create a user with a given `userId` and send them a message before they launch your app.
