### ISSUE TITLE
Crash on updating to 5.4.1

### ISSUE THREAD

**Issue by ankit209** [smooch/smooch-android#104]
My app auto updated to sdk version 5.4.1 and it started crashing on launch. Below is the stacktrace:

11-10 02:21:41.277 27305 27305 E AndroidRuntime: FATAL EXCEPTION: main
11-10 02:21:41.277 27305 27305 E AndroidRuntime: Process: com.sharesmile.share, PID: 27305
11-10 02:21:41.277 27305 27305 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/MediaType;
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at io.smooch.core.b.a.b.<clinit>(Unknown Source)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at io.smooch.core.b.b.a(Unknown Source)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at io.smooch.core.b.b.a(Unknown Source)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at io.smooch.core.service.SmoochService.<init>(Unknown Source)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3194)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1580)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6165)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.MediaType" on path: DexPathList[[zip file "/data/app/com.sharesmile.share-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sharesmile.share-1/lib/arm, /system/lib, /vendor/lib]]
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
11-10 02:21:41.277 27305 27305 E AndroidRuntime: 	... 14 more

I reverted back to version 5.4.0 and the crash disappeared.

**Comment by wmora** [comment]
perhaps the SDK update makes your app exceed its method count and you need to [enable multidex](https://developer.android.com/studio/build/multidex.html#mdex-gradle)? See #91

**Comment by ankit209** [comment]
@wmora 
Multidex is already enabled in my application.

**Comment by scottymack** [comment]
Same crash happening to me

**Comment by wmora** [comment]
Thanks for reporting, the uploaded artifact's `pom` file was invalid. We've uploaded the right one but you'll need to remove the cached dependency in your local .gradle directory in order to download the updated artifact. Sorry for the inconvenience!
