### ISSUE TITLE
Update smooch to the latest play services

### ISSUE THREAD

**Issue by sluit** [smooch/smooch-android#106]
Hi, could smooch be updated to use the latest Play Services (currently 11.6.0)? Play services in apps using smooch are now limited to 11.0.4.

**Comment by wmora** [comment]
We'll update in a future release. 

Note that you can override the Google Play Services version provided by Smooch by providing the following in your app's `build.gradle` file:

```
// Your app dependencies
dependencies {
    compile 'com.google.android.gms:play-services-location:11.6.0'
    compile 'com.google.firebase:firebase-core:11.6.0'
    compile 'com.google.firebase:firebase-messaging:11.6.0'
    // other dependencies
}

**Comment by sluit** [comment]
Thank you for the information!
