### ISSUE TITLE
Manifest Conflicts (AppCompat Versioning Issues)

### ISSUE THREAD

**Issue by vladimirarevshatyan** [smooch/smooch-android#108]
The library's Appcompat version is lower than the last one (26.1.0) so my build gradle gives error about that.

During the build the merging of manifest is failing because same tag is being used in the library so I had to add an meta-data tag to override the values in my manifest, not a good practice!

Fix these!

**Comment by wmora** [comment]
You can override the support library version provided by Smooch in your app's dependencies. No need to override your manifest. You can do this by updating your app's `build.gradle` file.

```
def supportLibraryVersion = "26.1.0" // or the version you're using
def firebaseVersion = "11.8.0" // or the version you're using

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "com.android.support:appcompat-v7:${supportLibraryVersion}"

    // Smooch
    implementation 'io.smooch:core:5.+'
    implementation 'io.smooch:ui:5.+'

    // Libraries imported by Smooch
    implementation "com.android.support:recyclerview-v7:${supportLibraryVersion}"
    implementation "com.google.firebase:firebase-core:${firebaseVersion}"
    implementation "com.google.firebase:firebase-messaging:${firebaseVersion}"
    implementation "com.google.android.gms:play-services-location:${firebaseVersion}"

    // Your other app dependencies
}
```

(Note: substitute `implementation` with `compile` if you haven't updated your project to use Android plugin for Gradle 3.0)

**Comment by vladimirarevshatyan** [comment]
Well it is a solution, not best but still....Anyway Why do I need to do that in the case if you can keep your library up to date? You've better keep it up to date so I won't need to do extra unneeded changes to my build gradle
