### ISSUE TITLE
Whole Library Conflicts

### ISSUE THREAD

**Issue by vladimirarevshatyan** [smooch/smooch-android#109]
Well your library is full of conflicts!!!!! 

Conflict with firebase due to the old dependency of yours
Conflict with Appcompat
Conflict with support design

After overriding the values in my manifest
The build won't pass through to due  impossibility of dex merging....Well this library is horrible

How others even use this

**Comment by wmora** [comment]
See https://github.com/smooch/smooch-android/issues/108#issuecomment-359641886 for a solution to version conflicts
