### ISSUE TITLE
Messages not displaying until activity is stopped and started

### ISSUE THREAD

**Issue by karolzdebel** [smooch/smooch-android#116]
Messages sent to a user are not displaying until some sort of action produces an activity stop and start. A video link can be found here: https://youtu.be/bCAgfPkZ_7A with a demo of the bug, you can see that the messages sent from our web dashboard are delivered but fail to display in the Android app until it is backgrounded and foregrounded again, or the smooch image selection is opened and closed.

No errors are logged from smooch or other parts of the app when this happens, none that we've found or had access to at least. We are using the latest smooch version 5.12.1, target SDK is 27 however we have reproduced this issue with versions 26,25, and 24. The bug seems to occur across all OS versions from our testing.

**Comment by wmora** [comment]
Are you initializing the SDK from outside an `Application` class? If so, you may be missing an init step, see the [docs](https://docs.smooch.io/guide/native-android-sdk/#initialize-from-an-activity-class) for detail.

If you are initializing from an `Application` class, could you provide a sample project reproducing the issue?

Thanks

**Comment by karolzdebel** [comment]
Initialization is done within the Application class, I will try to provide a sample project shortly.

**Comment by karolzdebel** [comment]
Our team found the problem, it was caused by using a smooch app id with all characters switched to uppercase. Would be good to get some sort of an error response from the init() method to avoid this silent failure.
