### ISSUE TITLE
Unable to send image using slack

### ISSUE THREAD

**Issue by aboutgaurav** [smooch/smooch-android#121]
We have successfully integrated  smooch  in my android App. We are using Slack as a business system.

Our team is able to send text message successfully but they are having problem when they try to send image.

Any help and guide will be really helpful.
Thanks

**Comment by wmora** [comment]
What's the problem they're having exactly?

**Comment by aboutgaurav** [comment]
User is not receiving image when we try to sent it through slack. Where as text message are working properly.

**Comment by alavers** [comment]
How are you sending the images via Slack? Are you using the `/sk` command?

**Comment by wmora** [comment]
can you provide an example of the `/sk` command you are using to send images?

**Comment by aboutgaurav** [comment]
@wmora I am not able to use /sk command while sending image from slack.
Could you list down the steps required to send image.
Thanks

**Comment by wmora** [comment]
`/sk ![](http://url-of.the/image.jpg)`

Refer to [shorthand syntax](https://docs.smooch.io/guide/sending-images-and-buttons-shorthand/) in our docs for more info

**Comment by aboutgaurav** [comment]
I have tried the above mentioned command but that didn't work for me.
[I think sending image from slack to user is currently not supported.
](https://github.com/smooch/smooch-ios/issues/75)

**Comment by wmora** [comment]
do you mean sending an image to a user by uploading an image through Slack? If so, that's not supported as images hosted by Slack are protected and can't be retrieved. But images hosted elsewhere can be sent with the `/sk` command. 

Here's an example using the command `/sk ![](https://www.w3schools.com/w3css/img_lights.jpg)`

![shorthand-image](https://user-images.githubusercontent.com/2448046/41598743-2337c196-739f-11e8-84bf-b6332d9b3150.gif)

**Comment by aboutgaurav** [comment]
Yes we were trying to upload image through Slack.
Thanks

**Comment by caiosba** [comment]
We came up with a solution for that:
- Implement your own Slack app that uses the Events API
- When it's a file upload, download the file, upload to some public path and then call the Slack commands API to run the command `/sk ![](http://public-url-for.the/image.jpg)`
