### ISSUE TITLE
Extending ConversationActivity adds an extra space below the action bar

### ISSUE THREAD

**Issue by jstaahl** [smooch/smooch-android#122]
Hey guys,

It seems that creating an extension of ConversationActivity and launching it adds an extra unwanted space below the action bar.

I have extended ConversationActivity as the FAQ suggest is possible here:
https://docs.smooch.io/faq/android/

```
public class CustomConversationActivity extends ConversationActivity {
  // no overrides yet
}
```

I am then launching the activity with (since ConversationActivity.show() launches the smooch ConversationActivity):
```
activity.startActivity(new Intent(activity, CustomConversationActivity.class))
```

I am not overriding any methods in my child class yet, just extending ConversationActivity.

 **What is the current behavior?**
I am seeing an extra empty space (R.id.Smooch_actionBarSpace) below the action bar. This space does not show up when I launch the smooch ConversationActivity in the same manner.

 **What is the expected behavior?**
There should not be an empty space below the action bar.

 **Please tell us about your environment:**
- smooch 5.13.2
- Android 8.1.0

Note: I am trying to add a menu button to the action bar by overriding onCreateOptionsMenu(). If there is another way to add a button to the action bar other than extending ConversationActivity, I am open to that as well.

**Comment by wmora** [comment]
Your activity should either use Smooch's theme `@style/Theme.Smooch` or a theme that has the following:

```
<item name="windowActionBarOverlay">true</item>
<item name="android:windowActionBarOverlay">true</item>
```
