### ISSUE TITLE
Proguard issue with latest glide version

### ISSUE THREAD

**Issue by raylee4204** [smooch/smooch-android#132]
After updating glide to 4.9.0, and using the latest version of Smooch,

Proguard throws an error with the following:

Warning: io.smooch.ui.NotificationController: can't find referenced method 'com.bumptech.glide.RequestBuilder apply(com.bumptech.glide.request.RequestOptions)' in program class com.bumptech.glide.RequestBuilder
Warning: io.smooch.ui.widget.AvatarImageView: can't find referenced method 'com.bumptech.glide.request.RequestOptions placeholder(android.graphics.drawable.Drawable)' in program class com.bumptech.glide.request.RequestOptions
Warning: io.smooch.ui.widget.AvatarImageView: can't find referenced method 'com.bumptech.glide.RequestBuilder apply(com.bumptech.glide.request.RequestOptions)' in program class com.bumptech.glide.RequestBuilder
Warning: io.smooch.ui.widget.MessageView: can't find referenced method 'com.bumptech.glide.request.RequestOptions onlyRetrieveFromCache(boolean)' in program class com.bumptech.glide.request.RequestOptions
Warning: io.smooch.ui.widget.MessageView: can't find referenced method 'com.bumptech.glide.RequestBuilder apply(com.bumptech.glide.request.RequestOptions)' in program class com.bumptech.glide.RequestBuilder

Also noticed that you guys use an outdated version of Glide.

**Comment by wmora** [comment]
Thanks for reporting, looks like `4.9.0` introduces a breaking change in our SDK when `minifyEnabled` is set to `true`. We'll release a new SDK version with an updated version of Glide (we currently use 4.6.1)

**Comment by raylee4204** [comment]
@wmora I think you guys should keep up to date with other dependencies you're relying on them to avoid issues like this

**Comment by raylee4204** [comment]
Any update on this issue?

**Comment by maxoumime** [comment]
Any plan to move to the latest version of Glide soon? This library is used by a lot of people and you shouldn't keep them from updating their dependencies.

**Comment by wmora** [comment]
We plan on upgrading to the latest Glide version later this week. I'll let you know once released

**Comment by wmora** [comment]
[v5.17.0](https://github.com/smooch/smooch-android/releases/tag/5.17.0) uses Glide 4.9.0

**Comment by maxoumime** [comment]
Thank you! Updated
