### ISSUE TITLE
Update dependencies: appcompat

### ISSUE THREAD

**Issue by raylee4204** [smooch/smooch-android#134]
**What is the current behavior?**
Currently, Smooch uses 1.0.0 version of androidx.annotation and androidx.appcompat

 **What is the expected behavior?**

Update to 1.0.2

**Comment by wmora** [comment]
We're not importing any `androidx` libraries at the moment (at least not explicitly). As of release 5.18.0, the version used of appcompat and annotations is `28.0.0`, the last version from the support library.

Is this causing an issue in your app? If so, could please provide the androidx/support lib dependencies that you are using in your project? That will help us debug dependency resolution
