### ISSUE TITLE
Ability to override the default behavior when handling message action

### ISSUE THREAD

**Issue by anas-ambri** [smooch/smooch-android#14]
Hey guys,

Not sure if this was brought up already, but there does not seem to be possible to override the default behaviour of the Conversation delegate. In iOS, one can do set a delegate to do the following, for example:

```
- (BOOL)conversation:(SKTConversation *)conversation shouldHandleMessageAction:(SKTMessageAction *)action {
    if ([action.uri.absoluteString hasPrefix:@"special:"]) {
        //Do something special
        return NO;
    } else {
        return YES;
    }
}
```

Unfortunately, in Android, it seems that one must override the whole `Delegate` object:

```
Smooch.getConversation().setDelegate(new Conversation.Delegate() {
            @Override
            public void onMessagesReceived(Conversation conversation, List<Message> list) {
                
            }

            @Override
            public void onUnreadCountChanged(Conversation conversation, int i) {

            }

            @Override
            public void onMessageSent(Message message, MessageUploadStatus messageUploadStatus) {

            }

            @Override
            public void onInitializationStatusChanged(InitializationStatus initializationStatus) {

            }

            @Override
            public void onPaymentProcessed(MessageAction messageAction, PaymentStatus paymentStatus) {

            }

            @Override
            public boolean shouldTriggerAction(MessageAction messageAction) {
                return false;
            }

            @Override
            public void onCardSummaryLoaded(CardSummary cardSummary) {

            }

            @Override
            public void onSmoochShown() {

            }

            @Override
            public void onSmoochHidden() {

            }
        });
```

Since I am not interested in all the other methods, there is no way for me to use this without breaking the rest of the functionality. I feel that the solution might be to subclass the `ConversationActivity` class, and setting it as delegate, but that does not seem possible either.

**Comment by anas-ambri** [comment]
Update on this:

Had to subclass `ConversationActivity`, and set that as a delegate:
```
public class SupportActivity extends ConversationActivity {

    @Override
    public boolean shouldTriggerAction(MessageAction messageAction) {
        if (messageAction.getUri().startsWith("special:")) {
            //Do something special
            return true;
        } else {
            return super.shouldTriggerAction(messageAction);
        }
    }
}

Smooch.getConversation().setDelegate(new SupportActivity());
```
This seems to do the trick, but I am not sure if it would break something internally. Any ideas?

**Comment by alavers** [comment]
Hey Anas!

>Since I am not interested in all the other methods, there is no way for me to use this without breaking the rest of the functionality.

I'm not sure what you mean here, can you clarify? Overriding the delegate object with empty implementations (for the void methods at least) shouldn't break any functionality.

**Comment by anas-ambri** [comment]
Hey Andrew,

So yeah, reading through it again, I definitely wasn't clear enough.
Here is my understanding of how Smooch initialization works:
1- When `init` is called, a new "SmoochManager" is created. This manager takes care of launching the service, listens to the Application lifecycle, and does all the bookkeeping for the queue system. (Note that "SmoochManager" might not be the name of the actual class internally; this is just a name I made up, since the code is obfuscated).
2- This manager takes care of creating the `Conversation` object.
3- Finally, `ConversationActivity` implements the `Delegate` interface. This suggests that it is the `ConversationActivity` that is used as delegate at some point. (This is my assumption).
4- Based on the previous assumption, then, at some point, between `init` and `ConversationActivity.show()` are called, `ConversationActivity` must be set as the `Delegate`. 

Now, to the problem:
- I can't seem to find at which point `ConversationActivity` (or any other object) becomes the `Delegate`. The natural place would be inside the `onCreate` of `ConversationActivity`, but there is nothing there.
- I haven't been able to find any other class that implements `Delegate` other than `ConversationActivity`.
- My understanding is that `Conversation` has a single reference to its `Delegate`. Thus, when providing a new object as `Delegate` (through `Smooch.getConversation().setDelegate()`), it is the delegate that was set last that gets called back. (As opposed to, say, listeners, where you can have plenty of them).

Now, say I wanted to change the behaviour of Smooch when a `MessageAction` is received I would have to set the delegate myself, after my `init`:

```
Smooch.init(this, "TOKEN");
Smooch.getConversation().setDelegate(new Conversation.Delegate() {
            @Override
            public void onMessagesReceived(Conversation conversation, List<Message> list) { }

            @Override
            public void onUnreadCountChanged(Conversation conversation, int i) { }

            @Override
            public void onMessageSent(Message message, MessageUploadStatus messageUploadStatus) { }

            @Override
            public void onInitializationStatusChanged(InitializationStatus initializationStatus) { }

            @Override
            public void onPaymentProcessed(MessageAction messageAction, PaymentStatus paymentStatus) { }

            @Override
            public boolean shouldTriggerAction(MessageAction messageAction) { 
                 if(messageAction.getUri().startsWith("special:") {
                       return false;
                 } else {
                      //Call super to handle the other cases
                 }
            }

            @Override
            public void onCardSummaryLoaded(CardSummary cardSummary) { }

            @Override
            public void onSmoochShown() { }

            @Override
            public void onSmoochHidden() { }
        });
```

Now, as you can see, there is no way for me to use the `super` implementation of delegate. Basically, `ConversationActivity`'s implementation of `Delegate` is not called here. This is bad, because `ConversationActivity` is probably doing very important stuff in all these methods. This was the gist of what I put on that first comment.

The only alternative is to subclass `ConversationActivity`, and override only the behaviour that I want to change (thus, my `SupportActivity`). Passing this as the delegate requires doing this:

`Smooch.getConversation().setDelegate(new SupportActivity());`

which, to me, feels wrong, because:
- You are not supposed to call `new` on an Activity object
- What happens if `setDelegate` is called some time later? (I don't know when that is done, so I don't have any way to confirm)
- This feels very iOS-y, with an Activity implementing a `protocol`.

I feel that I have been reading way too much into all of this, and that the solution is probably simpler. Plus, the code works, so I hope you are able to see where my confusion is stemming from.

**Comment by jugarrit** [comment]
Hey Anas, sorry it's taken us so long to get back to you.
The `ConversationActivity` does in fact implement the delegate, but it is a separate delegate from the one you will be overriding by calling `setDelegate()`. 

For our `ConversationActivity`, we are using the method [`setSmoochUiDelegate()`](http://docs.smooch.io/api/android/io/smooch/core/Conversation.html#setSmoochUIDelegate-io.smooch.core.Conversation.Delegate-) and it is being called in the activity's `onPause`.

As long as you stick to using `setDelegate()`, you will not run into any problems :)
