### ISSUE TITLE
Properly include all dependencies

### ISSUE THREAD

**Issue by hdodenhof** [smooch/smooch-android#17]
Please include all the necessary dependencies in your libraries pom.xml so they don't have to be added manually. In your docs it says you don't include these dependencies as "[..] many applications already feature [them]" which doesn't seem like a valid argument as the Gradle dependency management takes care of this.

ref http://docs.smooch.io/android/#android-studio-with-gradle
> Smooch depends on a few external libraries that many applications already feature. For this reason, it does not bundle those dependencies inside the AAR or JAR packages.

**Comment by jugarrit** [comment]
@hdodenhof could you elaborate on "Gradle dependency management takes care of this"?
When you add Smooch as a dependency, you are receiving a built version of the library, so we didn't want to force any specific versions  of those popular libs on people.

**Comment by hdodenhof** [comment]
Well, you wouldn't force a specific version of a lib on people, as the aar you ship would only include the dependency as a reference - and the version of this reference is subject to being changed by the Gradle dependency resolution strategy.

If you would for example add `gson:2.3.1` as a dependency to smooch and I would have an app that depends on smooch and `gson:2.4.0`, Gradle would also choose to use `gson:2.4.0` to resolve the dependency of your library as that's the newer version.

**Comment by jugarrit** [comment]
@hdodenhof currently the libraries we're referring to are marked as being provided at compile-time using gradle's `provided` scope.

Forgive my lack of understanding here, but are you saying that if I include these libraries normally (using `compile` scope) apps which include Smooch can also have these libs in their `compile` scope and gradle will not download these dependencies for Smooch?

I'm struggling to understand what the use of the `provided` scope is if this is the case.

**Comment by hdodenhof** [comment]
Basically, yes. Gradle will download a dependency only once regardless of how many times it is referenced as a direct or transitive dependency and it'll choose the most recent referenced version (that's the default behavior).

`compile` is what you want to use for regular dependencies, while `provided` would be used for dependencies that are provided by the runtime-environment (rarely used in Android projects).

**Comment by jugarrit** [comment]
Awesome!
Thanks :)

**Comment by jugarrit** [comment]
Done in v3.0.0
