### ISSUE TITLE
Update okhttp library

### ISSUE THREAD

**Issue by raylee4204** [smooch/smooch-android#18]
okhttp library has made several updates so far but smooch is still using 2.4.0

**Comment by jugarrit** [comment]
@raylee4204 you're free to include whatever version you want in your application, it should all be fine.
We will update the dependency in the future.

**Comment by raylee4204** [comment]
Using okhttp3 will fail when proguard is on

**Comment by jugarrit** [comment]
Ahh yes, okay.
We will bump the major version when we have a chance.

Thanks.

**Comment by ykostova** [comment]
I am having the exact same issue as @raylee4204 due to the way Square had changed their package for the newest versions of OkHttp. I am looking forward to an update as my hands are tied at the moment. Is there an ETA on the update?

**Comment by jugarrit** [comment]
Don't currently have an ETA, but I'll +1 this task in our backlog and keep you guys updated.

**Comment by raylee4204** [comment]
Does the latest build fix this?

**Comment by lawgimenez** [comment]
I'm having an error on this one, I'm using the new Square library version too at compile 'com.squareup.okhttp3:okhttp:3.3.1'

**Comment by jugarrit** [comment]
Working on the update as we speak.
Sorry for such a long wait!

**Comment by jugarrit** [comment]
Done!
