### ISSUE TITLE
Action button elevation is being clipped horizontally

### ISSUE THREAD

**Issue by hdodenhof** [smooch/smooch-android#19]
The elevation of a material action button is being clipped horizontally.
See attached screenshots for a regular and a pressed button state.

![clipped_btn](https://cloud.githubusercontent.com/assets/1824223/14748304/46a52c8e-08b9-11e6-99bd-fd4b26ccabed.png)
![clipped_btn_pressed](https://cloud.githubusercontent.com/assets/1824223/14748307/48652600-08b9-11e6-866a-fa8303bd91dd.png)

**Comment by jugarrit** [comment]
Hey @hdodenhof!
Do you mean to say that the shadow is being clipped?
We'll definitely look into this, thanks for reporting!

**Comment by hdodenhof** [comment]
Yup, that's what I meant.
