### ISSUE TITLE
Ability to automate messaging

### ISSUE THREAD

**Issue by Saketme** [smooch/smooch-android#20]
Hello, is it possible to auto-reply to user's message within the app? For example, in response to a button click.

Update: Okay, so looks like this can be done using `Conversation.sendMessage()`. However, the new message does not show up in the conversation until it's restarted. What am I missing?

Update 2: Turns out, `sendMessage()` is for sending messages on behalf of the user. Anything to reply them?

**Comment by alavers** [comment]
Yeah, the SDK's API is meant to expose actions that the end user can do. If you want to send auto-replies on behalf of your app, and have those messages sync'd across devices (and platforms), then you can use the Smooch REST API:

http://docs.smooch.io/rest/#post-message

To trigger a specific response when a button is pressed, you can send a postback button, and listen to the event with a Smooch webhook:

http://docs.smooch.io/android/#postbacks
http://docs.smooch.io/rest/#webhook-triggers

HTH

**Comment by Saketme** [comment]
REST APIs will do. Thank you :)
