### ISSUE TITLE
 Unable to start service Intent

### ISSUE THREAD

**Issue by prashant31191** [smooch/smooch-android#25]
Unable to start service Intent { cmp=io.smooch.demoapp/io.smooch.core.service.SmoochService } U=0: not found

when i run this code on eclipse then it will gives above Error, and doesn't connect my phone.But on andorid studio it will working well.

**Comment by prashant31191** [comment]
i think issues of the jar file like
// Add Smooch core and ui
    compile 'io.smooch:core:latest.release'
    compile 'io.smooch:ui:latest.release'
i didn't have latest jar file

**Comment by jugarrit** [comment]
Should be fixed with newest version 3.2.1. Re-open if you're still experiencing issues.

**Comment by prashant31191** [comment]
Thank you @jugarrit it's done now
