### ISSUE TITLE
Smooch with Fcm instead of Gcm: crash error

### ISSUE THREAD

**Issue by langhoangal** [smooch/smooch-android#26]
Hello,

I'm migrating my app to Firebase Cloud Messaging instead of GCM. Then i got the error below:

FATAL EXCEPTION: IntentService[GcmRegIntentService]                                                              java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/iid/InstanceID;
at io.smooch.core.GcmRegistrationIntentService.onHandleIntent(Unknown Source)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)

What can i do in this case? And will smooch work with Fcm?

**Comment by jugarrit** [comment]
Hello

To my knowledge, it won't be possible to make Smooch work with FCM. We do however have plans to upgrade in the future, so sit tight.
Sorry for the inconvenience!

**Comment by langhoangal** [comment]
Sorry for pushing, but when do you have plan to support FCM in the near future?! please!

**Comment by FlorinTufan** [comment]
@jugarrit Have you made any progress with this issue? :)

**Comment by tme-matei** [comment]
@jugarrit any updates on this? Google is strongly pushing us away from GCM and we're already using a lot of firebase's modules.

**Comment by lawgimenez** [comment]
Our app with Firebase is going live in months, and we are using GCM, but would like to switch to FCM before. We need timeline for this one.

**Comment by jugarrit** [comment]
We're working on this and should have an update available in the coming weeks

**Comment by jugarrit** [comment]
FCM implemented in the newest version. 
Enjoy :)

**Comment by tme-matei** [comment]
Grrrreat! Thanks!

**Comment by winz-playdribble** [comment]
awesome all of the sudden old "import io.smooch.core.GcmService" was erroring started digging and hey i see "import io.smooch.core.FcmService" 

awesome
