### ISSUE TITLE
Android studio support

### ISSUE THREAD

**Issue by okpatil4u** [smooch/smooch-android#3]
As per https://developer.android.com/tools/help/adt.html, google is ending support to eclipse adt. Is there any way to use this repo with android studio ?

**Comment by dannytranlx** [comment]
Hi there,

Our repo is mostly holding informations, demo apps and our core packages if you need to download them manually and integrate them by yourself. 

We do recommend to integrate Smooch through `gradle` by adding the following to your `.gradle` file which the recommend way to integrate dependencies *with* Android Studio.

```
compile 'com.google.android.gms:play-services-gcm:7.5.0'
compile 'com.google.code.gson:gson:2.3.1'
compile 'com.squareup.okhttp:okhttp:2.4.0'
compile 'io.smooch:core:latest.release'
compile 'io.smooch:ui:latest.release'
```

You can find more details over [our docs](http://docs.smooch.io/android/#adding-smooch-to-your-app) or the [README](https://github.com/smooch/smooch-android/blob/master/README.md) file.

So yes, **we do support Android Studio**, but you need to add Smooch in your `.gradle` file and it will download itself though [JCenter](https://bintray.com/smoochorg/maven/smooch/view). Here's more informations on [Gradle](http://developer.android.com/tools/building/configuring-gradle.html) :grin:
