### ISSUE TITLE
Can't initialise Smooch 

### ISSUE THREAD

**Issue by rosarioconti** [smooch/smooch-android#30]
Description:
While running my app with smooch I'm unable to start it and initialise it
I have followed the example for android. But I have also used for ios with no issue.

Results:
I keep getting this error: 
"An unexpected error occurred when validating the app token. Retrying in 10 seconds..."

Steps:
 1) I have tried the demo app and everything works fine 
 2) I add the same init , dependencies etc etc to my app. but then I get that error.

    compile 'com.google.code.gson:gson:2.4'
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'io.smooch:core:latest.release'
    compile 'io.smooch:ui:latest.release'

Note: 
 I have tried several combination for google service up to 9.0.2 and at this point I can't find the solution, which I have tried with the demo app and all seems fine.

- The google-service plugin in my gradle is added at the end.

For the conflicts and merge sake
- I use crashlytics, onesignal, facebook, parse libs.

**I was just wondering what's actualy smooch doing to get this error and debug a bit more, since it is obfuscated I can't take it really seriously at:**

"               
....
               } else if(var1.a() == 404) {
                    SmoochService.this.a(InitializationStatus.InvalidToken);
                    Log.e("SmoochService", "No app was found matching the supplied app token. Please make sure you have entered it correctly.");
                   } else {
                    int var2 = SmoochService.this.h.b();
                    if(SmoochService.this.C != io.smooch.core.service.a.Connected) {
                        SmoochService.this.y = true;
                        SmoochService.this.B = InitializationStatus.Unknown;
                    } else {
                        Log.e("SmoochService", String.format("An unexpected error occurred when validating the app token. Retrying in %d seconds...", new Object[]{Integer.valueOf(var2)}));
                        SmoochService.this.a(InitializationStatus.Error);
                        SmoochService.this.a(SmoochService.this.b, (long)(var2 * 1000));
                    }
                }
"

Thanks

**Comment by jugarrit** [comment]
Please retry with the latest instructions and re-open the issue if the problem persists.
