### ISSUE TITLE
Smooch sent rotated images when take portrait photos

### ISSUE THREAD

**Issue by fly1232008** [smooch/smooch-android#31]
Gradle dependencies
`compile 'io.smooch:core:latest.release'
compile 'io.smooch:ui:latest.release'`

Samsung Galaxy S6(Android 6.0.1) was used for testing.

attachment: video with reproducing  non-correct action
[https://www.youtube.com/watch?v=TZfD_l9_HJA](https://www.youtube.com/watch?v=TZfD_l9_HJA)

**Comment by dannytranlx** [comment]
Hi @fly1232008, thanks for the bug report, we will take a look at it! 😄

**Comment by fly1232008** [comment]
please send me message when will be fixed it =))

**Comment by skolarianer** [comment]
@jugarrit, I assume you need to evaluate the EXIF information of the shot.

> The camera driver may set orientation in the EXIF header without rotating the picture. Or the driver may rotate the picture and the EXIF thumbnail.

source: https://developer.android.com/reference/android/hardware/Camera.Parameters.html#setRotation(int)

We use an approach similar to this in our app: http://stackoverflow.com/a/11081918

Just my two cents.

**Comment by jugarrit** [comment]
Thanks for the info! This will help a lot.

**Comment by jugarrit** [comment]
This is fixed since https://github.com/smooch/smooch-android/releases/tag/5.8.0
