### ISSUE TITLE
Change color theme for send button

### ISSUE THREAD

**Issue by lawgimenez** [smooch/smooch-android#32]
The color themes XML can all be edited to our custom theme, except the "send" button it is still in violet, do you have any idea how?

**Comment by dannytranlx** [comment]
The send button is an image and isn't affected by the xml, we will properly change that in the future, but meanwhile, you can find the `smooch_btn_send_normal.png` in your `drawables` and change it with an image editor.

See
http://docs.smooch.io/android/#styling-the-conversation-interface
