### ISSUE TITLE
Override push notification start activity not working

### ISSUE THREAD

**Issue by quanvh3** [smooch/smooch-android#33]
Hi there, 
I've read that i'll be able to have Smooch notification to start my activity instead of ConversationActivity of smooch. However, even if i followed guideline to declare my activity in string.xml or settings.xml ( i tried both) but nothing seem to work. Am i doing something wrong or is there any tricks here ? 
http://docs.smooch.io/android/#notification-action-intent-override

 Thanks

**Comment by jugarrit** [comment]
No tricks, all you should have to do is override the string as stated in the docs.
To get some more help on this issue, please email the team at help@smooch.io and we'll get you sorted :)

**Comment by Arsyady** [comment]
Hi,

Sorry for bumping this. I just found the same issue. Seems the package path is incorrect in my case, so the notification opened default ConversationActivity. Hope this helps someone who find the same issue.
