### ISSUE TITLE
Google Play Services 7.5.0 out of date please upgrade to 9.4.0

### ISSUE THREAD

**Issue by erwasambo** [smooch/smooch-android#34]
Hello,
I love smooch(infact, I have been using it since it was supportkit.io) however of late, I when I was implementing Firebase services(which is now included in play services by default) there has been a sharp conflict between firebase and smooch and I would love to use both services. Please let me know if at all you will be fixing this issue any time soon.

**Comment by jugarrit** [comment]
In the progress of adding this now!

**Comment by jugarrit** [comment]
Done in 4.0.1!
