### ISSUE TITLE
Manifest merger failure with version 4.0.0 related to FileProvider usage

### ISSUE THREAD

**Issue by kaciula** [smooch/smooch-android#35]
Hi. I am seeing the following error when trying to build with smooch version 4.0.0

Manifest merger failed : Attribute provider#android.support.v4.content.FileProvider@authorities value=(com.tmy.own.package.name.fileprovider) from AndroidManifest.xml:127:13-59
  	is also present at [io.smooch:ui:4.0.0] AndroidManifest.xml:41:13-60 value=(io.smooch.ui.fileprovider).
  	Suggestion: add 'tools:replace="android:authorities"' to <provider> element at AndroidManifest.xml:125:

It seems the smooch library is using the FileProvider but my app is also using it. I am not sure if I use tools:replace if I am affecting the behavior of the smooch library.

What do you use the FileProvider for?

**Comment by jugarrit** [comment]
We are using the FileProvider in order for the user to be able to capture images.
Could you try version 4.0.1 and let me know if the issue is fixed? I changed the authority value slightly and I have a feeling it might resolve the issue.

**Comment by raylee4204** [comment]
This is still failing.

**Comment by kaciula** [comment]
@jugarrit I think the issue is that you are using the FileProvider inside the library. This means any app that uses the FileProvider cannot use your library. There must be only one 
`<provider android:name="android.support.v4.content.FileProvider"` 
inside the final merged AndroidManifest.

**Comment by jugarrit** [comment]
Ahhhh, I see... Thanks for the info. I'll make sure this is fixed tomorrow.

**Comment by jugarrit** [comment]
See https://github.com/smooch/smooch-android/releases/tag/4.0.2 for instructions on how to correctly replace the Smooch `FileProvider`.

**Comment by nothingimportant55** [comment]
Could you update the code example in the guide linked to above to explain what "authoritiesString" is?

Thanks

**Comment by Darrenzyq** [comment]
I also countered the same problem when building my project, here is the error description : 
Attribute provider#android.support.v4.content.FileProvider@authorities at AndroidManifest.xml:149:13-52 requires a placeholder substitution but no value for <filesAuthority> is provided.

**Comment by shtefanilie** [comment]
I experienced something similar to this when trying to build android version using [react-native-smooch](https://github.com/smooch/react-native-smooch) and [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob).  What I did, I added in my main `AppManifest.xml` file a new `<provider>` tag and set up some replace/merge rules. Below, my solution:
```
         <provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true"
            tools:replace="android:authorities">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths"
                tools:replace="android:resource"/>
        </provider>
```
