### ISSUE TITLE
Cannot find symbol GcmService

### ISSUE THREAD

**Issue by lawgimenez** [smooch/smooch-android#36]
I'm using the code
`GcmService.triggerSmoochGcm(intent.getExtras(), context);`

but seems to me the new Smooch SDK has deprecated this class

**Comment by mspensieri** [comment]
Starting in version 4.0.0 GCM was replaced by FCM. If your application requires GCM support, you'll need to stay on the 3.x branch.

```
compile 'io.smooch:core:3.2.2'
compile 'io.smooch:ui:3.2.2'
```

If you don't actually need GCM support, you can use the new FCM method instead:

```
FcmService.triggerSmoochNotification(intent.getExtras(), context);
```

**Comment by lawgimenez** [comment]
![smooch-fcmservice](https://cloud.githubusercontent.com/assets/7910468/17831890/c3260814-6728-11e6-8480-c48e1f683c89.PNG)

It has a compile error
