### ISSUE TITLE
FcmService triggerSmoochNotification compile error

### ISSUE THREAD

**Issue by lawgimenez** [smooch/smooch-android#37]
Since you guys closed my previous issue, it has a compile error.

![smooch-fcmservice](https://cloud.githubusercontent.com/assets/7910468/17831910/2b0b1fdc-6729-11e6-80cb-d959d7fe6a30.PNG)

**Comment by mspensieri** [comment]
Can you provide some more information? What is the compile error you are getting?

In your previous issue you stated

> I'm extending GcmReceiver

Does this mean your app is using GCM? You cannot mix GCM and FCM implementations - if your app is using GCM, you need to say on 3.x

**Comment by lawgimenez** [comment]
Previous Smooch version, app has its own GcmReceiver implemented like 

`<receiver android:name=".receivers.SmoochGcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="com.example" />
            </intent-filter>
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
            </intent-filter>
        </receiver>`

and the class is

`public class SmoochGcmReceiver extends GcmReceiver {

    private static final String TAG = SmoochGcmReceiver.class.getSimpleName();

    @Override
    public void onReceive(Context context, Intent intent) {
        Log.d("Smooch", "Received something = " + intent.getExtras().toString());
        SmoochObserver.getInstance().messageReceived(intent);
        MyApplication.getInstance().getSharedPref().edit().putBoolean(MyApplication.KEY_MESSAGE_RECEIVED, true).apply();
        FcmService.triggerSmoochNotification(intent.getExtras(), context);
    }
}`

where do triggerSmoochNotification should be placed? previous `GcmService.triggerSmoochGcm(intent.getExtras(), context);` worked

**Comment by jugarrit** [comment]
Hey @lawgimenez!

Since moving to FCM, the signature for this method was changed slightly. 
This should have been reflected better in the release notes, but you must now call it with a `Map` that holds the data.

For example:

```java
@Override
public void onMessageReceived(final RemoteMessage message) {
    final Map data = message.getData();

    triggerSmoochNotification(data, this);
}
```

Hope that helps :)
