### ISSUE TITLE
ConversationFragment very buggy

### ISSUE THREAD

**Issue by IlyaEremin** [smooch/smooch-android#44]
I often see "Could not connect to the server" message on top of screen.
Also, when I send messages from web to mobile app I don't see them until activity pause\resume.
I tried `ConversationActivity` and all works fine, but I have to use fragment because I need navigation drawer on top of chat and custom toolbar.
Also, when I add `ConversationFragment` it has top margin. And my screen looks like (from top to bottom) toolbar -> blank space -> chat. Could you please rid off this margin? Or make it customizable.

**Comment by jugarrit** [comment]
We don't currently support the use of `ConversationFragment` on its own.
Support could potentially be added in the future, but for now I suggest you use the `ConversationActivity`.
