### ISSUE TITLE
ConversationActivity crashing when rendering smoochButtons

### ISSUE THREAD

**Issue by carlosdejavite** [smooch/smooch-android#45]
For api version 16 and when you send an action button to the user, the ConversationActivity crashes due to java.lang.ArrayIndexOutOfBoundsException: length=16; index=17 at android.widget.RelativeLayout$LayoutParams.addRule(RelativeLayout.java:1204)
at io.smooch.ui.widget.MessageView.addSmoochButton

**Comment by IlyaEremin** [comment]
duplicate of #43

**Comment by jugarrit** [comment]
Closing since it's a dupe
