### ISSUE TITLE
Transmit more recognizable device names

### ISSUE THREAD

**Issue by skolarianer** [smooch/smooch-android#47]
What about using [this library](https://github.com/jaredrummler/AndroidDeviceNames) for more recognizable device names? I'm using this library in our app and it works like a charm. It's as simple as `DeviceName.getDeviceName()`.
E.g. for the 1. Generation Motorola Moto G it gives `Moto G (1. Gen)` instead of `Moto G`.

**Comment by wmora** [comment]
Will close as GH issues are for bug reports only. If you still want to request this feature, please visit [our help page](https://smooch.io/help/)
