### ISSUE TITLE
Add Changelog.md file in the repo

### ISSUE THREAD

**Issue by ravikumar-n** [smooch/smooch-android#50]
Please consider adding the changelog.md file and update the info for each release. Gives app developers clear view about what's changed in the library and the severity of the issue, before upgrading the production builds.

**Comment by mspensieri** [comment]
We post detailed release notes with each new version, found here https://github.com/smooch/smooch-android/releases.

Can you explain what would make a changelog easier to use?

**Comment by ravikumar-n** [comment]
My mistake I was looking for the changelog file repository section, forgot to check with the Release section.
