### ISSUE TITLE
Give us more power on UI

### ISSUE THREAD

**Issue by IlyaEremin** [smooch/smooch-android#51]
The main point is customize chat UI. For example give us method that returns root view so we could call `getRootView().findViewByid(R.id.camera).setVisibility(View.GONE)`.
In my case I need `DrawerLayout` to add right side menu and one custom button to open it.

**Comment by IlyaEremin** [comment]
Ok, forget about it, I just hack layout hierarchy and did what I need.

**Comment by aesparzagarcia** [comment]
@IlyaEremin how you did that hack?

**Comment by IlyaEremin** [comment]
@aesparzagarcia I wanted to add `DrawerLayout` to chat screen. So I created Activity which inherits from `ConversationActivity`. In `onCreate` I call following code:
```
ViewGroup rootView = ((ViewGroup) findViewById(android.R.id.content));
View oldChatLayout = rootView.getChildAt(0);
rootView.removeView(oldChatLayout);
View newChatLayout = LayoutInflater.from(this).inflate(R.layout.screen_chat, rootView);
((ViewGroup) newChatLayout.findViewById(R.id.chat_container)).addView(oldChatLayout, 1);
```
Where `R.layout.screen_chat` has following structure:
```
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.DrawerLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/drawer"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
>

    <FrameLayout
        android:id="@+id/chat_container"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
    />

    <FrameLayout
        android:id="@+id/side_panel_container"
        android:layout_width="240dp"
        android:layout_height="match_parent"
        android:layout_gravity="end"
    />

</android.support.v4.widget.DrawerLayout>
```

**Comment by IlyaEremin** [comment]
Also I just inspect `ConversationActivity` with Hierarchy Viewer to know views' ids

**Comment by cuiti** [comment]
@IlyaEremin thanks for the tip, it was a good idea.
In my case, I needed to add a FAB with some custom functionality to the chat layout. I downloaded the .aar and unzipped it to see the XML and IDs.
I also needed to redefine the `show()` methods in the subclass so that it started my CustomConversationActivity:

```
public static void show(Context var0) {
        show(var0, 0);
    }
public static void show(Context var0, int var1) {
        Intent var2 = new Intent(var0, CustomConversationActivity.class);
        if(var1 != 0)  var2.setFlags(var1);
        var0.startActivity(var2);
    }
```
