### ISSUE TITLE
Welcome message bug

### ISSUE THREAD

**Issue by IlyaEremin** [smooch/smooch-android#55]
I have following settings in smooch console:
<img width="1382" alt="screen shot 2016-11-01 at 17 52 48" src="https://cloud.githubusercontent.com/assets/1190759/19923863/d6efffda-a102-11e6-8c6e-70e435fb7d82.png">
So I expect user receive predefined message of first app launch.

When I first time start smooch sdk on android for new user I don't see any message.
If I send message from device then I see my message and then welcome message appears immediately.
Or when I close (remove from recent list) and open app again then I see welcome message.

ios sdk works fine for this case.

**Comment by almaziskhakov** [comment]
1

**Comment by IldusSadykov** [comment]
Have the same issue, it will be a blocker in 1 week for our release.

**Comment by jugarrit** [comment]
If you don't specify a specific event for a whisper we can't guarantee when it will be received. If you want the whisper to appear specifically when the app is launched, send it when "App is Launched".

![image](https://cloud.githubusercontent.com/assets/12450961/19974568/4a7bf802-a1bf-11e6-8ed3-5fd3bfd67619.png)
