### ISSUE TITLE
Chat not showing when system wide RTL

### ISSUE THREAD

**Issue by aghamdi** [smooch/smooch-android#57]
Once the Android system wide language have changed to a RTL (right to left) language like Arabic in my case. The chat stops showing just like this photo:

![6348cefa1fd484502faa508ea9249f6e](https://cloud.githubusercontent.com/assets/1574351/20033910/b3f4e370-a3bd-11e6-9093-a3f89551e5a9.jpg)

I'm using smooch latest release and google play services 9.4.0.

How can I fix it?

**Comment by wmora** [comment]
This has been fixed in version 4.0.7 of the SDK
