### ISSUE TITLE
Double Notifications

### ISSUE THREAD

**Issue by rajapulau** [smooch/smooch-android#64]
I was overriding notification smooch with FCM but I got two notif, one from FCMservice and one of them from smooch default notification. how to disable default notification coming from smooch ?

**Comment by jugarrit** [comment]
Hey @rajapulau 
Do you think you could provide some steps to reproduce the issue so that I can look into it?
Maybe a code sample?

Thanks.

**Comment by rajapulau** [comment]
Hi, @jugarrit 

I just add service FirebaseMessagingService on my app. example:

`public class NotificationsFirebaseMessagingService extends FirebaseMessagingService {
...
 @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
                        Intent intent = new Intent(this, PreSmoochActivity.class);
                        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP | Intent.FLAG_ACTIVITY_NEW_TASK);
                        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
                                PendingIntent.FLAG_UPDATE_CURRENT);

                        Uri defaultSoundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
                        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
                                .setTicker(text)
                                                      .setLargeIcon(BitmapFactory.decodeResource(getApplicationContext().getResources(), R.mipmap.ic_launcher))
                                .setSmallIcon(R.drawable.ic_notif)
                                .setContentTitle(name)
                                .setContentText(text)
                                .setPriority(10)
                                .setAutoCancel(true)
                                .setSound(defaultSoundUri)
                                .setContentIntent(pendingIntent);
                        vibrate();
                        NotificationCompat.InboxStyle notification = new NotificationCompat.InboxStyle(notificationBuilder);
                        NotificationManager notificationManager =
                                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
    }
...
}`

this is my screenshoot 
![screenshot_20170126-104215](https://cloud.githubusercontent.com/assets/958302/22319454/6822d208-e3b5-11e6-9031-6e9dcb549ab1.png)


I customize notification on method **onMessageReceived** . but I still get style notification from smooch on the top. how I disabled style notification from smooch ?  I want to show my customize notification only.

**Comment by aesparzagarcia** [comment]
Hi @rajapulau, I got same issue, did you solve it?

**Comment by jugarrit** [comment]
Sorry for taking so long to respond, I missed your comment somehow.
I'll add this issue to the backlog and let you know when we've made progress.

**Comment by jugarrit** [comment]
There is now a way to prevent the display of notifications via a new delegate.
See the javadoc for details.

https://docs.smooch.io/api/android/

**Comment by aesparzagarcia** [comment]
Thanks @jugarrit could you be more clear in your documentation please? Some example would be great. Thanks

**Comment by jugarrit** [comment]
Those are javadocs and I don't think it would be appropriate to add examples there.

Here's one:

```
package io.smooch.shellapp;

import android.app.Application;

import io.smooch.core.Conversation;
import io.smooch.core.Message;
import io.smooch.core.Settings;
import io.smooch.core.Smooch;

public class ShellApplication extends Application implements Conversation.MessageModifierDelegate {
    @Override
    public void onCreate() {
        super.onCreate();

        Settings settings = new Settings("<your_token>");
        Smooch.init(this, settings);

        Smooch.getConversation().setMessageModifierDelegate(this);
    }

    @Override
    public Message beforeSend(Message message) {
        return message;
    }

    @Override
    public Message beforeDisplay(Message message) {
        return message;
    }

    @Override
    public Message beforeNotification(Message message) {
        return null;
    }
}
```

**Comment by aesparzagarcia** [comment]
Awesome, thank u so @jugarrit worked nice!

**Comment by aesparzagarcia** [comment]
Hi @jugarrit, I got a new issue, when I´m  into ConversationActivity and I send a new message from email, I get the notification on my app, but I don´t see the message in real time into ConversationActivity, how can I solve this?

**Comment by jugarrit** [comment]
Are you making sure to return the message with the content intact in `beforeDisplay`?
If you return null here the message will be hidden.

**Comment by aesparzagarcia** [comment]
Yeah @jugarrit  I´m returning the message in beforeDisplay(Message message), only in beforeNotification I´m returning a null value, do you have another track?

**Comment by jugarrit** [comment]
Could you upload a code sample that reproduces the issue? It works fine for me.

**Comment by aesparzagarcia** [comment]
Sure, here is:

```
public class PushRegistrationMessagingService extends FirebaseMessagingService implements Conversation.MessageModifierDelegate {
@Override
public void onMessageReceived(RemoteMessage remoteMessage) {
Settings settings = new io.smooch.core.Settings(getResources().getString(R.string.smooch_key)); Smooch.init(getApplication(), settings);

Smooch.getConversation().setMessageModifierDelegate(this);

JSONObject jObj = null;
        try {
        jObj = new JSONObject(data.get("message"));
        String body = jObj.getString("text");

        onShowSmoochNotification(body);
    } catch (JSONException e) {
        e.printStackTrace();
    }
}
private void onShowSmoochNotification(String body){

        Intent intent = new Intent(this, io.smooch.ui.ConversationActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);

        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
                PendingIntent.FLAG_ONE_SHOT);

        Uri defaultSoundUri = RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
                .setSmallIcon(R.drawable.ic_notification)
                .setContentTitle(getString(R.string.app_name))
                .setContentText(body)
                .setAutoCancel(true)
                .setStyle(new NotificationCompat.BigTextStyle().bigText(body))
                .setSound(defaultSoundUri)
                .setColor(ContextCompat.getColor(getApplicationContext(),R.color.primary_dark))
                .setContentIntent(pendingIntent);

        NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

        notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());

    }

}
```

**Comment by jugarrit** [comment]
Where are you initializing Smooch? If you could send me a `zip` of your full application it would help me greatly.

**Comment by aesparzagarcia** [comment]
Sure, could you share an email please?

**Comment by jugarrit** [comment]
Can you send it to help@smooch.io?
Paste a link to this issue in the email please.

Thanks

**Comment by aesparzagarcia** [comment]
@jugarrit  I have sent the project, best regards, any question just let me know it please.

**Comment by aesparzagarcia** [comment]
@jugarrit  Hi Julia, do you have any update about my project?

**Comment by Go-Fred** [comment]
Hey! We haven't received your e-mail. What's your e-mail address? Can you please retry to send it to us?

**Comment by aesparzagarcia** [comment]
@Go-Fred  Sure my email armando_eg13@hotmail.com, send me something and I´ll reply you
