### ISSUE TITLE
Message rendering width

### ISSUE THREAD

**Issue by skolarianer** [smooch/smooch-android#65]
The received message (a whisper in this case) is being rendered too narrow. I’ve recognized this behaviour since release 4.2.0

![screenshot_20170125-030627](https://cloud.githubusercontent.com/assets/6286711/22275337/5dca6fc8-e2ac-11e6-8989-fb19e465cd12.png)

However, pausing and resuming the activity (actually switching to the home screen and back) fixes this issue. Destroying und re-creating the smooch activity reproduces the strange rendering.

![screenshot_20170125-030752](https://cloud.githubusercontent.com/assets/6286711/22275338/5dcbd49e-e2ac-11e6-8e54-07fd06020864.png)

**Comment by skolarianer** [comment]
Just ran a test with release 4.1.1: no rendering issues.

**Comment by wmora** [comment]
We'll take a look at it. Thanks for reporting

**Comment by wmora** [comment]
[v4.2.1](https://github.com/smooch/smooch-android/releases/tag/4.2.1) has been released with the fix
