### ISSUE TITLE
Please provide a static close method

### ISSUE THREAD

**Issue by norman-kapschefsky** [smooch/smooch-android#66]
Hi,
I really like to have ```ConversationActivity.close()``` method to dismiss smooch programmatically if opened. I wondered why there isn't already a function like this.

Use case:
We are sending deep links to our users to reach a certain point within the app. In theses cases we need to close Smooch so that the user sees the content change immediately.

Hope this can be done quickly. Shouldn't be that complicated ;)

Best. Norman.

**Comment by jugarrit** [comment]
Done in https://github.com/smooch/smooch-android/releases/tag/4.5.0
