### ISSUE TITLE
How to use ConversationFragment in Smooch

### ISSUE THREAD

**Issue by lddatacom** [smooch/smooch-android#67]
Hi there, 

According to my understanding, from version 4.4.0 ConversationFragment is introduced. However, searching around but I couldn't find any sample or documentation about how to use it. Ideally, I want to open a new fragment rather than a new activity as using ConversationActivity.show(...);

Thanks.

**Comment by jugarrit** [comment]
Hey @lddatacom 

`ConversationFragment` has always existed as part of the SDK, but we don't currently support the usage of it outside the `ConversationActivity`. 

You'll have to stick to using that activity for now, although for some small customization you may extend from that Activity instead.

Sorry for the inconvenience!
