### ISSUE TITLE
Initialise Smooch in different places

### ISSUE THREAD

**Issue by dtrikam1** [smooch/smooch-android#68]
Is it possible to initialise different bots (Different App tokens) in a single application based on a code/password the user has input? Currently this is not possible since it is recommended to place this file in the application class. Currently the user will input the code/password after the onCreate() in the application class and hence, this is where the problem arises.

**Comment by jugarrit** [comment]
Hey @dtrikam1, unfortunately it's not possible to have two different apps initialized at different points in the application...

If it's possible to have the bot react differently depending on the properties set on the user, you can use that to achieve something similar.

Hope that helps.
