### ISSUE TITLE
Make permission ACCESS_FINE_LOCATION optional

### ISSUE THREAD

**Issue by skolarianer** [smooch/smooch-android#72]
In 4.3.0 you introduced the location share feature. Therefore your SDK needs ACCESS_FINE_LOCATION permission. We don't need that feature in our app.
That's not an issue with users using Android 6 and above, since they only have to grant that permission when really needed. But Android 5 users complain about this additional permission.

Please make the use of location sharing optional.

At the moment we use
```java
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" tools:node="remove" />
```
to get rid of that permission. But isn't that somehow rude and ugly? :wink: 

Here is a nice story about this issue in general (it's not about your SDK):
https://medium.com/glucosio-project/how-libraries-can-silently-add-permissions-to-your-android-app-620911d7de6c

**Comment by jugarrit** [comment]
We'll consider this in a future release! Thanks for the feedback.

**Comment by condesales** [comment]
I have the same feedback to give, but with ```<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />```
Permissions requirements should be optional if possible.

**Comment by wmora** [comment]
Will close as GH issues are for bug reports only. If you still want to request this feature, please visit [our help page](https://smooch.io/help/)
