### ISSUE TITLE
Notification should not be displayed when user is on ConversationActivity

### ISSUE THREAD

**Issue by aesparzagarcia** [smooch/smooch-android#75]
When you are in ConversationActivity and you get new message, notification should not be displayed

**Comment by jugarrit** [comment]
Could you include a version and code sample that reproduces the issue?

**Comment by aesparzagarcia** [comment]
Sure @jugarrit here is the link where u will find my project https://www.dropbox.com/s/f00vy008nk581jt/SmoochFirebase.rar?dl=0

**Comment by aesparzagarcia** [comment]
Hi @jugarrit , have you seen my code? Do you have any update?

**Comment by jugarrit** [comment]
I haven't had a chance to look at it yet, sorry!
It'll probably be some time next week.

**Comment by jugarrit** [comment]
Hey @aesparzagarcia 
I took a look at the project you sent me and it seems that many of the bugs you're reporting are related to the way you're handling push notifications in your messaging service. 
If you could forward any further questions you have about these problems to hello@smooch.io our customer success representative will be happy to help you sort it out.

For now, I'll close these issues.
