### ISSUE TITLE
Detect if message is not sent

### ISSUE THREAD

**Issue by viettanbkdn** [smooch/smooch-android#77]
Can I know if message is not sent, ie no internet connection or server error...
Current code:

```
Conversation conversation = Smooch.getConversation();
if (conversation != null) {
        Message message = new Message(text);
        conversation.sendMessage(message);
}
```

**Comment by wmora** [comment]
Hi there :wave:. You need to provide a delegate somewhere in your app via [`setDelegate`](https://docs.smooch.io/api/android/io/smooch/core/Conversation.html#setDelegate-io.smooch.core.Conversation.Delegate-) and check the [message status](https://docs.smooch.io/api/android/io/smooch/core/MessageUploadStatus.html) in [`onMessageSent`](https://docs.smooch.io/api/android/io/smooch/core/Conversation.Delegate.html#onMessageSent-io.smooch.core.Message-io.smooch.core.MessageUploadStatus-). See https://github.com/smooch/smooch-android/issues/59#issuecomment-283667234 for an example on how to add the delegate
