### ISSUE TITLE
Chat Reply

### ISSUE THREAD

**Issue by aesparzagarcia** [smooch/smooch-android#78]
When i got a new notification and I click on it opens my app, but shows this pop up 
![screenshot_20170511-114714](https://cloud.githubusercontent.com/assets/9982524/25962089/1c20ed42-3642-11e7-9e57-07c2c72302c8.jpg)

Actually on notification, instead body message appears Chat Reply 
![img_123654684](https://cloud.githubusercontent.com/assets/9982524/25962407/3d91a6e6-3643-11e7-9d15-212771c599d8.png)

**Comment by jugarrit** [comment]
I'm afraid I don't understand the problem you're having.
When you tap the push notification, it opens your app? Not the conversation?
And when the app opens, it triggers another notification?

Are you using our notifications, or crafting your own?

If you open the app on notification tap, when the SDK initializes it will realize the user hasn't read the conversation and trigger a notification. Usually tapping a notif will open the conversation, so the notification will not be triggered.

**Comment by jugarrit** [comment]
Closing this as per https://github.com/smooch/smooch-android/issues/75#issuecomment-300867564

**Comment by aesparzagarcia** [comment]
I´m using my  own notification, using Firebase. It´s weird ´cause on stage release works fine, but when I change the build variant to production it´s when I got this error.
