### ISSUE TITLE
markAllAsRead() issue

### ISSUE THREAD

**Issue by viettanbkdn** [smooch/smooch-android#80]
1. Sent 3 messages to Smooch chat
--> `getUnreadCount()` returns `3`
2. `markAllAsRead()`
--> `getUnreadCount()` returns `0`
3. Clear data in App Setting (or re-install app)
--> `getUnreadCount()` returns `3`

I think when we `getUnreadCount()`, it should be `0` because user has already read the messages.

**Comment by jugarrit** [comment]
It is best to listen to the [onUnreadCountChanged] callback and react to changes there.
The value in `getUnreadCount()` will fluctuate as the SDK receives new data from the server.
