### ISSUE TITLE
Why do I need to call Smooch.init() in my Application class?

### ISSUE THREAD

**Issue by justincpollard** [smooch/smooch-android#81]
Most third-party libraries' `init()` methods take `Context` as an argument, but `Smooch.init()` takes `Application`. Is there a reason for this? It would be awesome if we could init with a `Context` instead, so initialization could take place somewhere other than a custom `Application` class.

**Comment by jugarrit** [comment]
The reason we require the initialization to occur in the Application is because initializing anywhere else can easily break the functionality of Smooch. Since the Application's `onCreate` is run before any other piece of code, we can ensure that Smooch is correctly initialized before the conversation window is displayed.

For example, if a Push Notification is tapped which opens the `ConversationActivity`, and the initialization doesn't occur in the Application, the user will end up in the conversation window without being initialized.

**Comment by justincpollard** [comment]
Thanks for the response! Maybe I should have started with the problem I'm trying to solve: my team is using the Slack integration and needs to use multiple different slack channels for different purposes. We also need multiple sets of office hours (for support team in different timezones) or the ability to turn chat on or off with the click of a button. I thought we could solve this using 2 or more different Smooch apps and lazy load Smooch when we know where the user is chatting from and whether we want to allow chat in that area. We don't know that information until after the Application's onCreate method. Is there anything you can think of that might work in this situation?

**Comment by jugarrit** [comment]
Unfortunately what you're trying to do is not currently supported.
Sorry about that

**Comment by justincpollard** [comment]
@jugarrit ok, I understand. Still, I think I could satisfy my usecase if only `Smooch.init()` took an arbitrary `Context` and not `Application`. I understand the issues you're trying to avoid, but because developers can determine whether Smooch is initialized in multiple ways (setting a delegate, for example) it seems like we would gain flexibility from a change like that and still be able to handle the pitfalls by checking initialization status. Maybe you guys could even throw an exception if someone called `ConversationActivity.start()` before successful initialization?

**Comment by jugarrit** [comment]
If you understand the risks and are willing to deal with any complications, you could pass an instance of your `Application` from wherever it is that you’d like to initialize Smooch. We won’t block it, but we also can’t guarantee all will function as expected and we won’t be able to support you.

**Comment by justincpollard** [comment]
I did try that, but it seemed that Smooch wouldn't initialize for some reason. After building a minimal sample project, it seems that the error is somewhere in my code. Thanks for your help!
