### ISSUE TITLE
Delegate.onInitializationStatusChanged() not called when Smooch is initialized in a Fragment

### ISSUE THREAD

**Issue by justincpollard** [smooch/smooch-android#82]
This is a followup question to https://github.com/smooch/smooch-android/issues/81. I'm trying to initialize Smooch in my Fragment so I know certain information from my server before initialization occurs. Unfortunately, upon initialization, I'm not receiving the `Delegate.onInitializationStatusChanged()` callback, so I can't react when initialization is complete. I am, however, receiving the `Delegate.onMessagesReset()` and `Delegate.onUnreadCountChanged()` callbacks in that order. Interestingly, initializing Smooch in an Activity seems to work just fine.

Is this a bug? I've created a sample project illustrating the issue here:

https://github.com/justincpollard/SmoochLazyInit

**Comment by jugarrit** [comment]
Hey @justincpollard 
We do not support the initialization of Smooch outside the `Application`, and as such we can't help with any issues you face concerning this method.
