### ISSUE TITLE
Feature Request: Support multiple Slack channels

### ISSUE THREAD

**Issue by justincpollard** [smooch/smooch-android#83]
In light of https://github.com/smooch/smooch-android/issues/81 and https://github.com/smooch/smooch-android/issues/82 I'd like to request multiple slack channel support. Given that many companies have support needs that vary by region, product, or other segmentation, the need for segmented channels exists. My company, for example, needs to support customers in at least 3 different timezones and many more different markets. Each market requires market-specific knowledge, so someone answering chats in one area cannot support someone in another region. Supporting multiple slack channels would alleviate this issue.

**Comment by spasiu** [comment]
Hi @justincpollard thanks for outlining your use cases to us!

At the moment, our business system integrations, including Slack, don't really do this segmentation of customers into groups.

If it's worth the trouble to solve this problem, you could hack together a solution. You would:
1. Create a Slack bot that watches for new slack channels created by Smooch.
2. Add custom appUser properties in your mobile app tracking their market and or timezone.
3. When a new channel is created, the bot could parse the custom properties from the Slack channel and then do some sort of custom dispatch messaging in Slack to notify the right teams/people.

Here's an example of a similar hack done with Smooch and Slack https://github.com/smooch/Smooch-Slack-dispatcher.

Note, none of this is officially supported.

Best wishes!
