### ISSUE TITLE
How to change the toolbar text & button color?

### ISSUE THREAD

**Issue by justincpollard** [smooch/smooch-android#84]
If I would like to make the ConversationActivity's toolbar white, is there anyway to do the following:

1) Change the toolbar text color (to black, for example)?
2) Change the color of the send button?

Thanks!

**Comment by jugarrit** [comment]
See the "Styling the Conversation Interface" in the Android documentation:
https://docs.smooch.io/guide/native-android-sdk/

**Comment by justincpollard** [comment]
Ok, I'll go ahead and contact support. the documentation is pretty sparse and after trying each attribute specified there, none of them change the toolbar text color; it always seems to be white. It also seems like `Smooch_accent` colors the toolbar background and the send button, but there doesn't appear to be a way to color them separately.

**Comment by shehanGuruge** [comment]
@justincpollard hey there I am also facing the same issue. Any solution for this ??

**Comment by justincpollard** [comment]
@shehanGuruge Not that I remember. It's been years since I worked with Smooch, though, so the sdk may have changed.
