### ISSUE TITLE
critical bug

### ISSUE THREAD

**Issue by thoinx** [smooch/smooch-android#85]
Can you change your mode on the manifest:
 <activity
            android:name="io.smooch.ui.ConversationActivity"
            android:label="@string/Smooch_activityConversation"
            android:launchMode="singleTask"
            android:theme="@style/Theme.Smooch" />

I want to change launchMode="singleTask" to launchMode="standard". Because when I include your SDK to my apps, I get the issue: The apps always kill all activity when the user press device home button.

Thanks!

**Comment by wmora** [comment]
Hi!

What are you trying to accomplish exactly? I'm not sure I understand correctly, but `android:clearTaskOnLaunch` causes the behavior you're describing and we don't include that in our lib.

`launchMode="singleTask"` won't kill all activities when the user presses the home button. Instead, it creates a new task with the Activity on top. If an instance of the Activity already exists then the Intent is routed to that existing instance.

**Comment by thoinx** [comment]
sorry, my fault.
Thanks for support!
