### ISSUE TITLE
Build fails because of invalid color `null_color`

### ISSUE THREAD

**Issue by joluet** [smooch/smooch-android#88]
My build fails when I use Android Studio 3.0 with the latest gradle plugin `com.android.tools.build:gradle:3.0.0-alpha3`. The reason is that Smooch seems to define a color value that's invalid. To be specific there is this entry in my merged `values.xml`: 
```xml
<item name="null_color" type="color">234234</item>
```
And this makes the build fail. Can you please remove it from the library?

This is the error I get:

```bash
Error:Execution failed for task ':app:mergeDebugResources'.
> Error: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.internal.aapt.AaptException: AAPT2 compile failed:
  aapt2 compile -o /path-to-project/app/build/intermediates/res/merged/debug /path-to-project/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
  Issues:
   - ERROR: /path-to-project/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:290 invalid color
```

**Comment by wmora** [comment]
Removed the resource in version [4.6.2](https://github.com/smooch/smooch-android/releases/tag/4.6.2)

**Comment by vulieumang** [comment]
Just remove android/app/src/main/res/values/colors.xml
it will build success again.
I work with my flutter_launcher_icons: "^0.7.5"
