### ISSUE TITLE
Client receive messages already read

### ISSUE THREAD

**Issue by JcMinarro** [smooch/smooch-android#9]
After have a conversation with a user, if He unninstall and install again the aplication Smoochio show a new notification with the old message when he starts the applications.
If he installs the application in other devices but he has the same email the notification is shown too.

**Comment by dannytranlx** [comment]
Yes, this is a known side-effect/issue with supporting multi-user. The read state is stored locally on the device which means when he logs in a new device, all messages in the conversation are treated as new messages thus all those notifications.

We are working on storing the read state on server-side so this won't be happening anymore. We will update this issue when this is going to be deployed. It's an ongoing task right now.

**Comment by JcMinarro** [comment]
:+1:

**Comment by dannytranlx** [comment]
Hi @JcMinarro, sorry for the delay. This should be fixed now with the [latest release](https://github.com/smooch/smooch-android/releases/tag/2.1.3). We have integrated server-side unread count :smile:

**Comment by thutran01** [comment]
Hello , currently i have same as problem with @JcMinarro.I am using lastest version. Can you explain me about it?

**Comment by wmora** [comment]
@thutran01 what exactly is the issue you are having? Do you have the steps to reproduce? Note that messages won't be marked as read on the server until the user opens the chat UI

**Comment by thutran01** [comment]
So I have some conversation with a user and I read it already after that I unninstall and install again the aplication which interacted with smooch app. I get all message but all of them is unread. it's  exactly is the issue i still have.
