### ISSUE TITLE
Get unread count always returns 0

### ISSUE THREAD

**Issue by kurse** [smooch/smooch-android#92]
Hi! We are having this issue on Android when a user has unread messages. After calling the Smooch.init() function I receive the in-app notification on the unread message, which makes the unreadCount always return a 0 because seeing how it's implemented you seem to take into account if the notification was shown. This makes it so we can never get a proper unreadCount as it'll always return 0, making it impossible for us to show the user the number of unread messages, and not even if he has unread messages or not. I hope you have a suggestion for us to get around it or hopefully have a fix in the way. Thank you!

**Comment by jugarrit** [comment]
`getUnreadCount()` is not a reliable way of always having the most up to date value as often it could be called before a message is received or in your case before the SDK has completed initialization.

Instead, it would be better to use `Conversation.Delegate` [onUnreadCountChanged](https://docs.smooch.io/api/android/io/smooch/core/Conversation.Delegate.html#onUnreadCountChanged-io.smooch.core.Conversation-int-) to keep track.
