### ISSUE TITLE
Smooch send button UI

### ISSUE THREAD

**Issue by mychaelgo** [smooch/smooch-android#94]
smooch_btn_send_normal.png does not appear according to drawables

![media-20170925](https://user-images.githubusercontent.com/4651658/30796501-8b725084-a1fc-11e7-85c9-ffc56112f38a.png)

**Comment by wmora** [comment]
hmm can't reproduce it, which version of the sdk are you using?

**Comment by mychaelgo** [comment]
@wmora 5.0.0

**Comment by jugarrit** [comment]
@mychaelgo are you overriding the drawable for the send button by any chance? If so, that should no longer be necessary as we will tint the image based on your primary color.
