### ISSUE TITLE
Readme should not advises to use "latest" tag

### ISSUE THREAD

**Issue by philippeauriach** [smooch/smooch-android#95]
In the Readme it is said to use the following in the gradle file :
```
compile 'io.smooch:core:latest.release'
compile 'io.smooch:ui:latest.release'
```
While this allows to be always up to date with the latest changes to the Smooch.io, it can also bring breaking changes without the developer knowing where it comes from.

Actually it just happened to me : opening Android project I did not open since a few weeks, gradle build fails without any changes. The cause : smooch got updated to v5, and brought with it support lib v26, which got into conflict with the v25 support libs I got in my project. This leads to dependencies problems, which are really painful to debug, somethings like the following : 

`Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:cardview-v7:26.0.0-alpha1] AndroidManifest.xml:24:9-38`

I think the Readme should be changed to a fixed version with each release. I know that on iOS Smooch provides a log message saying that a new version is available : this allow the developer to check for a new version, read the changelog, and know if and when to upgrade smooch library.

Thanks

**Comment by wmora** [comment]
We updated the README to reflect the latest major version and in the future we'll add the specific version with each release. Thanks for reporting!
