### ISSUE TITLE
Start converstation with predefined message

### ISSUE THREAD

**Issue by mychaelgo** [smooch/smooch-android#96]
Any plan start conversation activity with predefined message ?
for example :
```
ConversationActivity.show(Activity act, String message, boolean sendNow);
```

So developer just add message and set sendNow to true or false

**Comment by wmora** [comment]
If you want to send a message on behalf of the user you can call [`Conversation.sendMessage(Message)`](https://docs.smooch.io/api/android/io/smooch/core/Conversation.html#sendMessage-io.smooch.core.Message-). For the second case, we don't support pre-filling the message input at the moment. We've filed it as a feature request for the team to discuss
