### ISSUE TITLE
Can't connect to server

### ISSUE THREAD

**Issue by mychaelgo** [smooch/smooch-android#97]
```
    compile 'io.smooch:core:5.+'
    compile 'io.smooch:ui:5.+'
```

``` java
 // Smooch
        Settings smoochSettings = new Settings("APP_ID");
        Smooch.init(mApplication, smoochSettings, new SmoochCallback() {
            @Override
            public void run(Response response) {
                Log.d(TAG, "Response smooch: " + response.getError());
            }
        });
```

get error
```
Response smooch: Smooch app id was invalid. Either the id is empty, or permissions for this app have been revoked.
```
even i change my APP_ID to APP_TOKEN, it didn't work

![screenshot_20171002-120615](https://user-images.githubusercontent.com/4651658/31068052-5ef095be-a780-11e7-8887-a4a4bd5dc8eb.png)

**Comment by Scythe14** [comment]
If you store your ID in some constant string, you should do a Clean Project and before and then Make project. This might fix your problem.

**Comment by mychaelgo** [comment]
@Scythe14 still didn't work

**Comment by orino76** [comment]
I am getting the same error with the latest release (5.0.1) It was working properly before upgrading to 5.0.

Can someone help to share a solution? Thank you,

**Comment by jugarrit** [comment]
@orino76 if you started seeing this problem after upgrading, is it possible you are still using the app token to initialize instead of the app ID? Not that these values are not the same and the app token will no longer work. See https://github.com/smooch/smooch-android/releases/tag/5.0.0 for more details on the changes.

@mychaelgo I can confirm that init does indeed work with a regular app ID. If you share your app ID, I can help try to debug the issue.

**Comment by orino76** [comment]
@jugarrit I have replaced the token with app ID but the problem is still there...Don't know how to identify the cause as it just said that the ID is invalid.

**Comment by jugarrit** [comment]
@orino76 which device are you using?

**Comment by orino76** [comment]
@jugarrit Samsung Note 5, tried on the emulator and it is the same

**Comment by jugarrit** [comment]
@orino76 can you share your ID here so I can help debug?

**Comment by orino76** [comment]
@jugarrit I have sent my id to your email. Thank you for your help.

**Comment by spasiu** [comment]
The appToken was being passed at init instead of an appId. This was due to some confusion in our documentation between old SDKs and new SDKs.

**Comment by sheikh987** [comment]
> I have the same problem

`      

        Settings settings = new Settings(YOUR_APP_ID);

        String jwt = Jwts.builder()
                .claim("scope", "appUser")
                .claim("userId", USER_ID)
                .signWith(SignatureAlgorithm.HS256, SECRET)
                .setHeaderParam("kid", KEY_ID).compact();

        Smooch.init(getActivity().getApplication(), settings,null);

        Smooch.login(USER_ID, jwt, null);

        User.getCurrentUser().setFirstName(PROFILE_NAME);
        User.getCurrentUser().setEmail(PROFILE_LOGIN_EMAIL);

        sendButton = (Button) view.findViewById(R.id.send_button);

        sendButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                ConversationActivity.show(getActivity().getApplication());

            }
        });`
ERROR: 
`E/SmoochService: Login called with same userId/JWT combination. Ignoring!`
`E/SmoochService: Smooch app id was invalid. Either the id is empty, or permissions for this app have been revoked.`

**Comment by Vibinreji** [comment]
Hi @sheikh987 u found any solution.I am getting same issue  E/SmoochService: Login called with same userId/JWT combination. Ignoring!.kindly help me if u can

**Comment by RoydBOL** [comment]
Hey @sheikh987 and @Vibinreji , did you guys find any solution?
I'm facing the same issue.!!!
